### ISSUE TITLE
A wierd crash when decode jpeg image on Ubuntu env

### ISSUE THREAD

**Issue by chenzx** [libjpeg-turbo/libjpeg-turbo#472]
The crash backtrace:

#0  0x00007ffff36ed438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff36ef03a in __GI_abort () at abort.c:89
#2  0x00007ffff372f7fa in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff3848f98 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff373c6e8 in malloc_printerr (ar_ptr=0x0, ptr=<optimized out>, str=0x7ffff3848fc0 "munmap_chunk(): invalid pointer", action=<optimized out>) at malloc.c:5020
#4  munmap_chunk (p=<optimized out>) at malloc.c:2849
#5  __GI___libc_free (mem=<optimized out>) at malloc.c:2970
#6  0x000000000046a742 in free_pool ()
#7  0x0000000000453795 in jpeg_abort ()
#8  0x000000000045a8d1 in jpeg_finish_decompress ()
#9  0x0000000000435b19 in tjDecompress2 ()

Tried dynamic so and static lib link, both crashes the same. But the same code runs on Mac ok.

I thought it's due to function symbol conflict with other so libs(there's is an OpenCV so dynamic library link in the ubuntu app, while the Mac app isn't), but cannot catch the conflicting origin source.

**Comment by chenzx** [comment]
decode code is simple:

```
    size_t jpegSize{bytesLength}; //from caller args;
    uint8_t* jpegBuf = (uint8_t*)buffer; //from caller args;
    //
    tjhandle tjInstance = tjInitDecompress();
    if (!tjInstance) {
        return false;
    }
    int width, height;
    int inSubsamp, inColorspace;
    if (tjDecompressHeader3(tjInstance, jpegBuf, jpegSize, &width, &height,
                            &inSubsamp, &inColorspace) < 0) {
        tjDestroy(tjInstance);
        return false;
    }
    printf("DecodeJPEGBuffer: input jpegSize=%d image size=(%d, %d)\n", jpegSize, width, height);
    uint8_t *pixels = (uint8_t*)malloc(height * width);
    int flags = 0;
    if (tjDecompress2(tjInstance, jpegBuf, jpegSize,
                    (unsigned char*)pixels, width, 0/*pitch*/, height,
                    TJPF_RGB, flags) < 0) {
        free(pixels);
        tjDestroy(tjInstance);
        return false;
    }
```

**Comment by chenzx** [comment]
wait, my coworker has just found the problem using Valgrind:

```
uint8_t *pixels = (uint8_t*)malloc(height * width);
```

should be:

```
uint8_t *pixels = (uint8_t*)malloc(height * width * 3);
```

A terrible typo miss.
